# Use Kali Linux rolling as base image
FROM kalilinux/kali-rolling

# Update package list and install necessary tools and dependencies
RUN apt-get update && apt-get install -y \
    iputils-ping \
    net-tools \
    tcpdump \
    hping3 \
    iproute2 \
    iptables \
    python3 \
    python3-pip \
    pipx \
    python3-venv \
    vim \
    netcat-traditional \
    nmap \
    ethtool \
    dnsutils \
    python3-netfilterqueue \ 
    && apt-get clean && rm -rf /var/lib/apt/lists/*  # Install netfilterqueue using apt


# Install Scapy using pipx (recommended method for Kali)
RUN pipx install scapy

# Automatically activate the Scapy environment on container start
RUN echo 'source ~/.local/share/pipx/venvs/scapy/bin/activate' >> /root/.bashrc

# Copy attacker script to root directory
COPY attacker.py /attacker.py

# Create a directory for scripts
RUN mkdir -p /scripts

# Copy firewall script into the scripts directory
COPY ddosfirewall.py /scripts/ddosfirewall.py
COPY attackgen.py /attackgen.py
COPY icmponly.py /icmponly.py
COPY tcpsynonly.py /tcpsynonly.py
COPY udponly.py /udponly.py
COPY udplagonly.py /udplagonly.py
COPY udplagattack.py /udplagattack.py
COPY ddos_combined_attacker.py /ddos_combined_attacker.py
# Make scripts executable
RUN chmod +x /attacker.py /scripts/ddosfirewall.py

# Set working directory and default command
WORKDIR /
CMD ["/bin/bash"]
